### ISSUE TITLE
throw the phpexception, any ways to solve it?

### ISSUE THREAD

**Issue by a2htray** [mainlab-dev/chado_search#1]
`PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "chado.chado_search_sequence_search" does not exist LINE 1: SELECT distinct organism FROM chado.chado_search_sequence_se... ^: SELECT distinct organism FROM chado.chado_search_sequence_search ORDER BY organism; Array ( ) in chado_query() (line 1538 of /var/www/html/sites/all/modules/tripal/tripal_core/api/tripal_core.chado_query.api.inc).`

**Comment by chunhuaicheng** [comment]
It looks like you enabled the sequence search but removed the required materialized view. You can use 'drush' to recreate it:

cd <your web-root-dir>
drush csreload

This will recreate the missing materialized views defined in your 'chado_search/file/settings.conf'. You can then go to 'Tripal' > 'Chado Schema' > 'Materialized Views' to repopulate it using Tripal's job system.

**Comment by a2htray** [comment]
thanks a lot, it run well

**Comment by chunhuaicheng** [comment]
No problem. Glad to help. I'm going to close this thread but feel free to open new ones if you have more questions or feature requests.
