### ISSUE TITLE
:( there is one column not in table

### ISSUE THREAD

**Issue by a2htray** [mainlab-dev/chado_search#3]
![image](https://user-images.githubusercontent.com/12782530/31757167-5b1e6b7a-b4da-11e7-9c85-774afed3cfe6.png)

the column "landmark" not in the `chado_search_gene_search` table

**Comment by chunhuaicheng** [comment]
It looks like you're using a different version of 'gene search' from the default version. You'll need to use a different version of materialized view that corresponds to it as well. In such case, you'll need to adjust the 'file/settings.conf' accordingly and remove the old materialized view so the new one can be created. 

For example, if you're using the GDR version of gene search, you should have the following stanza in your 'file/settings.conf':

[Gene Search]
id=gene_search
path=search/genes
file=includes/search/gdr/gdr_gene_search.php
mview_name=chado_search_gene_search
mview_file=includes/mview/gdr/gdr_gene_search.mview.php
mview_callback=chado_search_create_gene_search_mview
enabled=1

You should notice the difference of 'mview_file' pointing to 'gdr_gene_search.mview.php'. You can then delete the old materialized view using the Tripal Admin interface and use 'drush csreload' to create the new materialized view and populate it by submitting a Tripal Job.

**Comment by a2htray** [comment]
good job, it works
